version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: your_user
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]

volumes:
  db:
    driver: local
