import React from 'react'
import Nav from 'app/layout/templates/nav'
import { Manrope } from 'next/font/google'

import Footer from './layout/templates/footer'

import './globals.css'

const manrope = Manrope({ subsets: ['latin'] })

export async function generateMetadata() {
  const favicon = await fetch('http://localhost:3000/api/globals/site-favicon')
  const data = await favicon.json()
  return { icons: data.favicon.url }
}

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   icons: '',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={manrope.className}>
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
